#ifndef APPROXSHADERLAB_GLOBAL_H
#define APPROXSHADERLAB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef APPROXSHADERLAB_LIB
# define APPROXSHADERLAB_EXPORT Q_DECL_EXPORT
#else
# define APPROXSHADERLAB_EXPORT Q_DECL_IMPORT
#endif

#endif // APPROXSHADERLAB_GLOBAL_H
